### PR TITLE
Added 'dest' arg to eos_command module

### PR DESCRIPTION
**Pull request by chepazzo**
This allows you to save the output of a command to a file.  It works with json and text encoding.

This is particularly useful when snapshotting configs (e.g. in an automated lab environment to automate switching between different topologies). This enhancement will also properly report if the dest file contents have changed.

### CODE REVIEW

**Comment by phil-arista** [comment]
Hi Mike,
As you know, we merged your last PR for the encoding option (which was a great idea). I'm a little hesitant about adding the file copy functionality.  I feel like the existing copy module does this really well (http://docs.ansible.com/ansible/copy_module.html). The core module takes care of idempotency and even allows file permissions and creating backups.  What do you think?

**Comment by chepazzo** [comment]
I've had problems with using the copy module. For one, I can't get it to support indents. This isn't really a huge deal if no humans are ever going to look at it, but it just doesn't feel clean. But the bigger issue is that my results keep truncating.

e.g. this only gives me ~10% of the result (128 lines instead of >1000):
```
  - name: save file
    copy:
      content="{{config.output.0.result.output}}"
      dest="configs/{{ inventory_hostname }}.conf"
```

I am definitely open to other suggestions, though.

**Comment by phil-arista** [comment]
I added 1000 port-channels to my switch to create some extra config and did this:

```
  tasks:
    - name: Get Running Config
      eos_command:
        commands='show version'
        encoding='text'
        connection={{ inventory_hostname }}
        debug=true
      register: output

    - set_fact: encoding="{{output.output.0.encoding}}"

    - template:
        src=config_template.j2
        dest="./{{ inventory_hostname }}.config"
```

Then config_template.js deals with a string or json object like so:

```
{% if encoding == 'text' %}
{{ output.output.0.result.output}}
{% else %}
{{ output.output.0.result | pprint() }}
{% endif %}
```

The template module is idempotent as well, so it should cover your use case.  Let me know if that works.

**Comment by chepazzo** [comment]
Ok, this seems to do the trick. It fails on --check because check_mode is not supported in eos_command, so the `output` var never gets written, but I can work around that.

thanks

**Comment by phil-arista** [comment]
Great! Yeah, you can add some ``when`` clauses to make sure vars are present before executing the task.  We've already updated the version info on your last PR, so we should be safe to close this PR.  Thanks again for your contributions!

**Pull request closed without merging**
